name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ["17", "21"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          java-package: "jre"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Test on ${{ matrix.os }} with python ${{ matrix.python-version }}
        run: uv run --all-extras --python-preference only-managed --python ${{ matrix.python-version }} pytest
