name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        java-version: ["21"]
        # python-version: ["3.10", "3.11", "3.12", "3.13"]

        include:
          - os: ubuntu-latest
            java-version: "21"
            python-version: "3.13t"

    steps:
      - uses: actions/checkout@v4

      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          java-package: "jre"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Test on ${{ matrix.os }} with python 3.10
        run: uv run --all-extras --python-preference only-managed --python 3.10 pytest

      - name: Test on ${{ matrix.os }} with python 3.11
        run: uv run --all-extras --python-preference only-managed --python 3.11 pytest

      - name: Test on ${{ matrix.os }} with python 3.12
        run: uv run --all-extras --python-preference only-managed --python 3.12 pytest

      - name: Test on ${{ matrix.os }} with python 3.13
        run: uv run --all-extras --python-preference only-managed --python 3.13 pytest

      - name: Test on ${{ matrix.os }} with python 3.13t
        if: matrix.os == 'ubuntu-latest'
        run: uv run --all-extras --python-preference only-managed --python 3.13t pytest
